# Generated by Django 6.0 on 2026-06-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kampanya Başlığı')),
                ('location', models.CharField(max_length=150, verbose_name='Bölge')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Hedef Tutar')),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Toplanan Tutar')),
                ('needs', models.TextField(blank=True, verbose_name='İhtiyaç Listesi')),
                ('official_link', models.URLField(blank=True, verbose_name='Resmi Bağış Linki')),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaigns/')),
                ('active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Bağış Kampanyası',
                'verbose_name_plural': 'Bağış Kampanyaları',
            },
        ),
    ]
