# Generated by Django 6.0 on 2026-06-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Ad Soyad')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Posta')),
                ('city', models.CharField(max_length=100, verbose_name='Şehir')),
                ('support_area', models.CharField(choices=[('saglik', 'Sağlık'), ('lojistik', 'Lojistik'), ('psikolojik', 'Psikolojik Destek'), ('arama_kurtarma', 'Arama Kurtarma'), ('diger', 'Diğer')], max_length=50, verbose_name='Destek Alanı')),
                ('message', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Başvuru Tarihi')),
            ],
            options={
                'verbose_name': 'Gönüllü Başvurusu',
                'verbose_name_plural': 'Gönüllü Başvuruları',
            },
        ),
    ]
