# Generated by Django 6.0 on 2026-06-14 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_volunteer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparednessCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_bag', models.BooleanField(default=False, verbose_name='Deprem çantam hazır')),
                ('meeting_area', models.BooleanField(default=False, verbose_name='Toplanma alanını biliyorum')),
                ('first_aid', models.BooleanField(default=False, verbose_name='İlk yardım çantam var')),
                ('family_plan', models.BooleanField(default=False, verbose_name='Aile afet planım hazır')),
                ('emergency_numbers', models.BooleanField(default=False, verbose_name='Acil telefonlar kayıtlı')),
                ('powerbank', models.BooleanField(default=False, verbose_name='Powerbank dolu')),
                ('flashlight', models.BooleanField(default=False, verbose_name='El fenerim hazır')),
                ('water_food', models.BooleanField(default=False, verbose_name='Su ve dayanıklı gıda hazır')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preparedness_check', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hazırlık Kontrolü',
                'verbose_name_plural': 'Hazırlık Kontrolleri',
            },
        ),
    ]
