# Generated by Django 6.0 on 2026-06-14 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_preparednesscheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Merkez Adı')),
                ('city', models.CharField(max_length=100, verbose_name='Şehir')),
                ('address', models.TextField(verbose_name='Adres')),
                ('capacity', models.PositiveIntegerField(default=100, verbose_name='Toplam Kapasite')),
                ('current_load', models.PositiveIntegerField(default=0, verbose_name='Mevcut Doluluk')),
                ('urgent_need', models.TextField(blank=True, verbose_name='Acil İhtiyaçlar')),
                ('active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centers', to='donations.campaign', verbose_name='Kampanya')),
            ],
            options={
                'verbose_name': 'Bağış Merkezi',
                'verbose_name_plural': 'Bağış Merkezleri',
            },
        ),
    ]
