# Generated by Django 6.0 on 2026-06-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donationcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcenter',
            name='manager',
            field=models.CharField(blank=True, max_length=150, verbose_name='Merkez Sorumlusu'),
        ),
        migrations.AddField(
            model_name='donationcenter',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='İletişim'),
        ),
        migrations.AddField(
            model_name='donationcenter',
            name='status',
            field=models.CharField(choices=[('dusuk', 'Düşük Yoğunluk'), ('orta', 'Orta Yoğunluk'), ('kritik', 'Kritik Yoğunluk')], default='dusuk', max_length=20, verbose_name='Yoğunluk Durumu'),
        ),
        migrations.AddField(
            model_name='donationcenter',
            name='working_hours',
            field=models.CharField(default='24 Saat', max_length=100, verbose_name='Çalışma Saatleri'),
        ),
    ]
