# Generated by Django 6.0 on 2026-06-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_donationcenter_manager_donationcenter_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcenter',
            name='map_link',
            field=models.URLField(blank=True, verbose_name='Harita Linki'),
        ),
        migrations.AddField(
            model_name='donationcenter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme'),
        ),
    ]
