# Generated by Django 6.0 on 2026-06-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_donationcenter_map_link_donationcenter_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcenter',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Enlem'),
        ),
        migrations.AddField(
            model_name='donationcenter',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Boylam'),
        ),
    ]
