# Generated by Django 6.0 on 2026-06-14 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_donationcenter_latitude_donationcenter_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Ad Soyad')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Posta')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('donation_type', models.CharField(choices=[('para', 'Para Bağışı'), ('urun', 'Ürün Bağışı')], max_length=20, verbose_name='Bağış Türü')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tutar')),
                ('product_description', models.TextField(blank=True, verbose_name='Ürün Bağışı Açıklaması')),
                ('message', models.TextField(blank=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Bağış Tarihi')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.campaign', verbose_name='Kampanya')),
            ],
            options={
                'verbose_name': 'Bağış',
                'verbose_name_plural': 'Bağışlar',
            },
        ),
    ]
