# Generated by Django 5.2.15 on 2026-06-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Posta')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Şehir')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
            },
        ),
    ]
